### PR TITLE
Added Emojis

### PR DESCRIPTION
**Pull request by PolarHacker**
Hello there! I added emojis next to each effect, and I also changed the text to reflect the same text found on iOS :-)

### CODE REVIEW

**Comment by PolarHacker** [comment]
Sorry; I'm rather new to how GitHub works in regards to forks and pull requests. I changed the bundle identifier name and README. Feel free to change it back 👍

**Comment by PolarHacker** [comment]
The emojis have been tweaked, with the README and bundle identifier name being reverted. :-)

**Comment by LumingYin** [comment]
Looks good to me! Merged :)

**Comment by PolarHacker** [comment]
Awesome, thanks! 😀

**Comment by PolarHacker** [comment]
Should the version number be updated? 🤔 Forgot to change that.

**Pull request merged**
